# Generated by Django 4.1.5 on 2023-04-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='secondary_school',
            new_name='school',
        ),
    ]
